# name: Deploy Notebooks from DEV to PROD

# on:
#   push:
#     branches:
#       - main  # You can customize this branch as needed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set Up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x  # Use the version you need

#       - name: Install Databricks CLI
#         run: pip install databricks-cli

#       - name: create token files
#         run: |
#           # save tokens
#           echo ${{ secrets.DEV_DATABRICKS_HOST }} > dev_token_file.txt
#           echo ${{ secrets.PROD_DATABRICKS_HOST }} > prod_token_file.txt
#           mkdir dev_notebooks

#       # - name: Deploy Notebooks 1 connect test
#       #   run: |
#       #     # Authenticate to DEV Databricks
#       #     databricks configure --host "$DEV_DATABRICKS_HOST"  --token-file dev_token_file.txt
        
#       - name: Deploy Notebooks 1 connect test 2
#         run: |
#           # Authenticate to DEV Databricks
#           databricks configure --host "${{ secrets.DEV_DATABRICKS_HOST }}"  --token-file dev_token_file.txt --debug

#       - name: Deploy Notebooks 1 connect
#         run: |
#           # Export notebooks from DEV workspace
#           databricks workspace export /Shared/DQ /dev_notebooks/ --debug

#       - name: Deploy Notebooks 2 connect 
#         run: |  
#             # Authenticate to PROD Databricks
#             databricks configure --host "${{ secrets.PROD_DATABRICKS_HOST }}"  --token-file prod_token_file.txt --debug
#             # Import notebooks to PROD workspace
#             databricks workspace import /dev_notebooks/DQ Shared --overwrite --debug

#     # env:
#     #   DEV_DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
#     #   DEV_DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
#     #   PROD_DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
#     #   PROD_DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}


name: Deploy Notebooks to Databricks PROD

on:
  push:
    branches:
      - main  # Modify this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the appropriate Python version

    - name: Export Notebooks from DEV
      run: |
        # Set up the Databricks REST API URL for your DEV workspace
        DEV_API_URL="${{ secrets.DEV_DATABRICKS_HOST }}/api/2.0/workspace/export?path=/Shared/DQ.py&format=SOURCE"

        curl -X GET "$DEV_API_URL" \
          -H "Authorization: Bearer $DATABRICKS_TOKEN_DEV" \
          -o DQ.py -v
      env:
        DATABRICKS_TOKEN_DEV: ${{ secrets.DEV_DATABRICKS_TOKEN }}

    # - name: unzip export.zip
    #   run: |
    #     # Unzip the exported files
    #     unzip -q export.zip -d dev_notebooks

    - name: Set up Databricks CLI for PROD
      run: |
        # Configure the Databricks REST API URL for your PROD workspace
        PROD_API_URL="${{ secrets.PROD_DATABRICKS_HOST }}/api/2.0/workspace/import"

        curl -X POST "$PROD_API_URL" \
          -H "Authorization: Bearer $DATABRICKS_TOKEN_PROD" \
          -F "path=/Shared/PROD/DQ.py" \
          -F "format=SOURCE" \
          -F "content=@DQ.py" \
          -o import_result.json -v
      env:
        DATABRICKS_TOKEN_PROD: ${{ secrets.PROD_DATABRICKS_TOKEN }}

    - name: Clean up
      run: |
        rm -rf dev_notebooks  # Remove temporary export directory
