name: Deploy Notebooks from DEV to PROD

on:
  push:
    branches:
      - main  # You can customize this branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the version you need

      - name: Install Databricks CLI
        run: pip install databricks-cli


      - name: test connect 2
        run: |
          # Authenticate to DEV Databricks
          echo "$DEV_DATABRICKS_HOST" 

      - name: Deploy Notebooks 1 connect 0
        run: |
          # Authenticate to DEV Databricks
          databricks configure --host "${{ secrets.DEV_DATABRICKS_HOST }}" --token 

          
      - name: Deploy Notebooks 1 connect
        run: |
          # Authenticate to DEV Databricks
          databricks configure --host "${{ secrets.DEV_DATABRICKS_HOST }}" --token < echo "$DEV_DATABRICKS_TOKEN"

      - name: Deploy Notebooks 1 export
        run: |
          # Export notebooks from DEV workspace
          databricks workspace export_dir Shared/DQ.py /tmp/dev_notebooks

      - name: Deploy Notebooks 2 connect 
        run: |  
            # Authenticate to PROD Databricks
            databricks configure --host "${{ secrets.PROD_DATABRICKS_HOST }}" --token < echo "PROD_DATABRICKS_TOKEN"
  
      - name: Deploy Notebooks 2 import
        run: |  
            # Import notebooks to PROD workspace
            databricks workspace import_dir /tmp/dev_notebooks Shared --overwrite

    # env:
    #   DEV_DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
    #   DEV_DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
    #   PROD_DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
    #   PROD_DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
